import { Project } from './types';

export const projects: Project[] = [
  {
    slug: 'aira-wallet',
    title: 'AIRA Wallet',
    oneLiner: 'Personal finance dashboard that tells you exactly how much you can spend — today, this week, and for the rest of the month',
    role: 'Full-Stack Developer & Product Designer',
    timeframe: 'March 2026',
    tech: ['Next.js 15', 'React 19', 'TypeScript', 'Tailwind CSS v4', 'Zustand', 'Clerk Auth', 'Google Gemini AI', 'Turso (libSQL)', 'Radix UI', 'Motion', 'date-fns', 'Vercel'],
    theme: {
      name: 'teal',
      accent: '#15F4D1',
      accentSoft: 'rgba(21, 244, 209, 0.1)',
      accentStrong: '#0D9B87',
      gradient: 'linear-gradient(135deg, #05060A 0%, #0A1612 50%, #15F4D1 100%)',
    },
    links: {
      live: 'https://aira-wallet-three.vercel.app/',
      github: 'https://github.com/JPBrill/AIRA-Wallet',
    },
    sections: [
      {
        id: 'context',
        label: 'Context',
        kind: 'context',
        content: 'Most budgeting tools show you what you already spent — not what you can safely spend right now. They lump all money together without accounting for timing: bills due this week, income arriving next week, and variable budgets all need separate treatment. The result is people either overspend because they see a large balance, or underspend out of anxiety because they have no clear signal. I wanted to build a single number you can trust: safe-to-spend, calculated in real time across three time horizons.',
      },
      {
        id: 'approach',
        label: 'Approach',
        kind: 'approach',
        content: 'I built the app around a three-layer budget model: Income Sources (what comes in and when), Fixed Commitments (must-pay recurring bills with due days and priority status), and Variable Categories (discretionary monthly budgets). A pure TypeScript finance engine — computeSafeToSpend, computeCategoryUsage, generateMonthlyPlan — runs the calculations independent of the UI, making it fully testable and reusable across views. A multi-step onboarding flow ensures the dashboard is fully populated before a user ever sees an empty state. The AIRA sci-fi design language was applied throughout: deep charcoal backgrounds, teal/cyan accents, glass-card panels, and interpolated progress bars that shift from green to amber to red as budgets fill up. Auth is handled by Clerk, and all data persists to a Turso (libSQL) serverless database — making it fully cloud-native and multi-device ready.',
      },
      {
        id: 'result',
        label: 'Results',
        kind: 'result',
        content: 'Shipped a fully functional, deployed personal finance app with persistent cloud storage, authentication, and real-time safe-to-spend calculations across three time horizons. Complete CRUD for all data types (income, commitments, categories, transactions, savings goals), a guided onboarding flow, global currency and week-start preferences, and a live production deployment. Built entirely online: AI Studio as IDE, Perplexity as architecture partner, GitHub for version control, Vercel for deployment.',
      },
      {
        id: 'reflection',
        label: 'Reflection',
        kind: 'reflection',
        content: "The best architectural decision was keeping the finance engine as pure TypeScript functions completely separate from the UI. It made the dashboard composable and the logic trivial to reason about — same inputs, same outputs, every time. Migrating from localStorage to Turso was the biggest inflection point: it turned a browser-only prototype into a real product. The AI Studio + Perplexity collaboration meant architecture and implementation happened simultaneously rather than sequentially, compressing the build timeline significantly.",
      },
    ],
    outcomes: [
      { label: 'Build Time', value: '~2 wks' },
      { label: 'Time Horizons', value: '3' },
      { label: 'App Routes', value: '9+' },
    ],
  },
  {
    slug: 'aira-pawn-pos',
    title: 'AIRA Pawn POS',
    oneLiner: 'Full-stack point-of-sale system for South African pawn shops — inventory, loans, customers, and legal compliance in one instrument-grade interface',
    role: 'Full-Stack Developer & Product Designer',
    timeframe: 'March 2026',
    tech: ['Next.js 15', 'React 19', 'TypeScript', 'Tailwind CSS v4', 'Zustand', 'NextAuth', 'Drizzle ORM', 'Neon Postgres', 'Google Gemini AI', 'Motion', 'Lucide React', 'Vercel'],
    theme: {
      name: 'amber',
      accent: '#F59E0B',
      accentSoft: 'rgba(245, 158, 11, 0.1)',
      accentStrong: '#B45309',
      gradient: 'linear-gradient(135deg, #05060A 0%, #130E02 50%, #F59E0B 100%)',
    },
    links: {
      live: 'https://aira-pawn-pos.vercel.app/',
      github: 'https://github.com/JPBrill/AIRA-PAWN-POS',
    },
    sections: [
      {
        id: 'context',
        label: 'Context',
        kind: 'context',
        content: 'South African pawn shops operate under strict legal frameworks — the Second-Hand Goods Act and National Credit Act require meticulous record-keeping for every acquisition, loan, and sale. Most operators rely on spreadsheets or generic retail software that ignores these compliance obligations entirely. The challenge was building a purpose-built POS that handles the full transaction lifecycle — from customer KYC capture to loan agreement generation — while feeling as calm and fast to use as a modern instrument.',
      },
      {
        id: 'approach',
        label: 'Approach',
        kind: 'approach',
        content: 'I structured the system around four core entities: Customers (with SA ID validation and address capture for legal compliance), Inventory (supporting both pawn and purchase workflows with condition grading), Loans (with due-date tracking, automatic status derivation — Active, Overdue, Redeemed, Forfeited — and an overdue warning system), and Documents (quotes and invoices with status tracking). A persistent Neon Postgres database via Drizzle ORM replaces localStorage entirely, making every record durable and queryable. The AIRA sci-fi design language was adapted into a pawn-shop-specific palette with an amber accent, and all interactive elements use a unified Squishy component system for consistent feel across the entire app.',
      },
      {
        id: 'result',
        label: 'Results',
        kind: 'result',
        content: 'Delivered a production-ready POS covering the full pawn shop workflow: customer intake with SA ID validation, item receive/purchase with linked customer or walk-in details, a loan management dashboard with automatic status tracking, a POS cart with barcode-scanner-compatible search, and a documents module for quotes and invoices. All data persists to Neon Postgres, auth is handled by NextAuth, and the app is deployed live on Vercel. Built entirely online using AI Studio, Perplexity, GitHub, and Vercel.',
      },
      {
        id: 'reflection',
        label: 'Reflection',
        kind: 'reflection',
        content: "The decision to unify all interactive elements under a single Squishy component system (SquishyButton, SquishyBadge, SquishyInput, SquishySelect) paid off — it meant every audit finding was a one-line fix rather than a global search-and-replace. The hardest part was modelling the legal register: every transaction needs an immutable snapshot of the customer and item at the time it occurred, not a live reference. If I were to extend this, I'd add PDF generation for loan agreements and a mobile-optimised view for the POS cart used at the counter.",
      },
    ],
    outcomes: [
      { label: 'Build Time', value: '~1 wk' },
      { label: 'Modules', value: '6' },
      { label: 'DB Tables', value: '4' },
    ],
  },
  {
    slug: 'loan-risk-ui',
    title: 'Loan Risk UI',
    oneLiner: 'ML-powered loan risk assessment interface — enter applicant details, run a live model, and get an AI-generated decision email with a safety check in one shot',
    role: 'Full-Stack Developer',
    timeframe: 'May 2026',
    tech: ['Next.js 16', 'React 19', 'TypeScript', 'Tailwind CSS v4', 'FastAPI (backend)', 'Machine Learning Model'],
    theme: {
      name: 'emerald',
      accent: '#10B981',
      accentSoft: 'rgba(16, 185, 129, 0.1)',
      accentStrong: '#059669',
      gradient: 'linear-gradient(135deg, #020B07 0%, #041A10 50%, #10B981 100%)',
    },
    links: {
      live: 'https://loan-risk-ui.vercel.app/',
      github: 'https://github.com/JPBrill/loan-risk-ui',
    },
    sections: [
      {
        id: 'context',
        label: 'Context',
        kind: 'context',
        content: 'Loan officers and fintech teams need to evaluate applicant risk quickly and consistently, without manually interpreting raw model outputs. A raw probability score means nothing to a non-technical reviewer — what they need is a clear risk label, a rationale, and a ready-to-send decision email. The challenge was bridging the gap between an ML scoring backend and a usable, trustworthy front-end interface that a human could confidently act on.',
      },
      {
        id: 'approach',
        label: 'Approach',
        kind: 'approach',
        content: 'I built a two-panel layout: an applicant input form on the left capturing all scoring features (age, income, credit score, DTI ratio, employment status, loan purpose, etc.) and a live results panel on the right. The form maps directly to the ML model\'s expected input schema — numeric fields for quantitative signals, dropdowns for categorical ones. On submission, the UI calls a FastAPI backend that runs the classifier, generates a decision email via LLM, and runs a safety check to flag whether human review is required. Risk policy (conservative vs. aggressive threshold) is selectable per-session, letting operators tune sensitivity without touching the model.',
      },
      {
        id: 'result',
        label: 'Results',
        kind: 'result',
        content: 'Delivered a functional loan assessment UI that integrates ML scoring, LLM-generated decision emails, and a safety review pipeline in a single request cycle. The results panel surfaces the risk label (high/low), default probability, policy threshold, a formatted email preview, and a human-review flag — giving operators everything they need to act on a decision without leaving the screen.',
      },
      {
        id: 'reflection',
        label: 'Reflection',
        kind: 'reflection',
        content: "The most valuable design decision was making risk policy configurable at the session level — conservative (0.5) vs. aggressive (0.4) threshold — rather than hardcoding it. It made the tool genuinely useful for teams with different risk appetites without requiring a backend change. The safety check layer, which flags emails for human review before they're sent, was also a key trust signal: it makes the AI feel like a reliable colleague rather than an autonomous actor.",
      },
    ],
    outcomes: [
      { label: 'Risk Policies', value: '2' },
      { label: 'Input Features', value: '12' },
      { label: 'Pipeline Steps', value: '3' },
    ],
  },
  {
    slug: 'agent-dashboard',
    title: 'Agent Dashboard',
    oneLiner: 'AI-powered task management interface that feels inevitable, not artificial',
    role: 'Product Designer & Engineer',
    timeframe: '2023 - 2024',
    tech: ['React', 'Next.js', 'OpenAI API', 'Tailwind CSS', 'Framer Motion'],
    theme: {
      name: 'cyan',
      accent: '#35BDF8',
      accentSoft: 'rgba(53, 189, 248, 0.1)',
      accentStrong: '#0284C7',
      gradient: 'linear-gradient(135deg, #0F172A 0%, #022C43 40%, #35BDF8 100%)',
    },
    sections: [
      {
        id: 'context',
        label: 'Context',
        kind: 'context',
        content: 'Teams managing autonomous AI agents face a cognitive overload problem: too many states, unclear reasoning chains, and no intuitive way to intervene when models drift. Traditional dashboards treat AI like APIs—just logs and metrics—when what people need is an interface that mirrors how they think about delegation and trust.',
      },
      {
        id: 'approach',
        label: 'Approach',
        kind: 'approach',
        content: 'I designed the dashboard around three core principles: (1) Show intent, not just activity—surface why an agent made a decision, not just what it did. (2) Progressive disclosure—basic view for monitoring, expanded view for debugging. (3) Opinionated defaults—agents should feel autonomous until intervention is genuinely needed. The UI uses a vertical timeline that makes agent reasoning scannable at a glance, with inline controls for pausing, steering, or rolling back.',
      },
      {
        id: 'result',
        label: 'Results',
        kind: 'result',
        content: 'Reduced average intervention time by 40% and increased task success rate to 94%. Users reported feeling more confident delegating complex workflows, and support tickets related to "agent confusion" dropped significantly. The timeline view became the most-used feature, with 89% of daily active users interacting with it.',
      },
      {
        id: 'reflection',
        label: 'Reflection',
        kind: 'reflection',
        content: "If I were to rebuild this, I'd add more opinionated guardrails earlier—users still struggled with over-steering agents in early versions. I'd also explore voice-based corrections for mobile contexts. What I'd keep: the principle of showing intent over activity. That single decision made the entire interface coherent.",
      },
    ],
    outcomes: [
      { label: 'Latency', value: '-40%' },
      { label: 'Task Success', value: '94%' },
      { label: 'Daily Active Users', value: '2.3k' },
    ],
  },
  {
    slug: 'notion-ai-companion',
    title: 'Notion AI Companion',
    oneLiner: 'Context-aware AI assistant that understands your Notion workspace',
    role: 'Product Designer & Engineer',
    timeframe: '2025',
    tech: ['Next.js', 'TypeScript', 'Notion API', 'OpenAI API', 'Tailwind CSS'],
    theme: {
      name: 'purple',
      accent: '#A855F7',
      accentSoft: 'rgba(168, 85, 247, 0.1)',
      accentStrong: '#7C3AED',
      gradient: 'linear-gradient(140deg, #0F0A1E 0%, #1E1537 50%, #A855F7 100%)',
    },
    sections: [
      {
        id: 'context',
        label: 'Context',
        kind: 'context',
        content: 'Notion users often juggle dozens of pages, databases, and notes, making it hard for generic AI assistants to provide relevant help. They lack context about your workspace structure, ongoing projects, and specific terminology. The challenge was building an AI that feels like it truly understands your workspace without being intrusive.',
      },
      {
        id: 'approach',
        label: 'Approach',
        kind: 'approach',
        content: "I designed a companion that builds a contextual map of your workspace through the Notion API, identifying key databases, recurring patterns, and relationships between pages. The AI uses this context to provide workspace-aware suggestions. The interface is a minimal side panel that appears only when summoned via keyboard shortcut, showing relevant suggestions based on the page you're currently viewing.",
      },
      {
        id: 'result',
        label: 'Results',
        kind: 'result',
        content: 'Beta users reported a 60% reduction in time spent searching for related pages and information. The context-aware suggestions had an 82% acceptance rate, significantly higher than generic AI tools. Users particularly valued the "quiet intelligence"—the AI stayed invisible until needed but was remarkably helpful when invoked.',
      },
      {
        id: 'reflection',
        label: 'Reflection',
        kind: 'reflection',
        content: "If I were to rebuild this, I'd add more granular privacy controls—some users wanted to exclude certain databases from AI analysis. I'd also explore proactive (but non-intrusive) suggestions when the AI detects patterns like \"You've been working on this document for 2 hours, here are related resources.\" What worked perfectly: the invisible-until-needed model. Users loved that it never interrupted their flow.",
      },
    ],
    outcomes: [
      { label: 'Search Time', value: '-60%' },
      { label: 'Acceptance Rate', value: '82%' },
      { label: 'Beta Users', value: '450+' },
    ],
  },
  {
    slug: 'calm-writing-tool',
    title: 'Calm Writing Tool',
    oneLiner: 'Distraction-free AI writing assistant that feels like a trusted collaborator',
    role: 'Solo Developer & Designer',
    timeframe: '2024 - Present',
    tech: ['React', 'Next.js', 'Claude API', 'Framer Motion', 'Tailwind CSS'],
    theme: {
      name: 'orange',
      accent: '#F97316',
      accentSoft: 'rgba(249, 115, 22, 0.1)',
      accentStrong: '#C2410C',
      gradient: 'linear-gradient(145deg, #0B1020 0%, #1E293B 50%, #F97316 100%)',
    },
    sections: [
      {
        id: 'context',
        label: 'Context',
        kind: 'context',
        content: 'Most AI writing tools feel intrusive—constant suggestions, autocomplete interrupting your flow, features competing for attention. Writers need space to think, not another thing demanding cognitive bandwidth. The challenge was creating an AI assistant that enhances focus rather than breaking it.',
      },
      {
        id: 'approach',
        label: 'Approach',
        kind: 'approach',
        content: 'I designed a minimal, typography-first interface where the AI acts as a subtle collaborator. The core principle: AI suggestions appear only when explicitly requested via keyboard shortcuts, never automatically. The UI uses a single-column layout with generous spacing, muted colors, and smooth micro-interactions. Focus mode removes all chrome except the text itself.',
      },
      {
        id: 'result',
        label: 'Results',
        kind: 'result',
        content: 'Reached 10k+ active users with 5M+ words written in the first six months. User feedback consistently highlighted the "calm" feeling—people reported being able to write for longer sessions without mental fatigue. The keyboard-first interaction model became the defining feature, with 78% of users relying primarily on shortcuts rather than clicking UI elements.',
      },
      {
        id: 'reflection',
        label: 'Reflection',
        kind: 'reflection',
        content: "If I were to rebuild this, I'd add more nuanced AI tone controls earlier—users wanted to adjust formality and style without breaking flow. I'd also explore ambient audio cues for AI availability. What I'd keep: the principle of opt-in AI assistance. That single constraint shaped everything else and made the tool genuinely calm.",
      },
    ],
    outcomes: [
      { label: 'Active Users', value: '10k+' },
      { label: 'Words Written', value: '5M+' },
      { label: 'Avg Session', value: '47min' },
    ],
  },
];
